apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-master
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "C:\Users\samir\Desktop\Work\Scalable_Jenkins_K8s\jenkins_master_pv"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-master
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
