apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
   name: jenkins-master
   namespace: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-master
subjects:
  - kind: ServiceAccount
    name: jenkins-master